# Generated by Django 6.0.3 on 2026-03-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
