# Generated by Django 6.0.3 on 2026-03-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_apartment_latitude_apartment_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourrequest',
            old_name='preferred_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='tourrequest',
            name='message',
        ),
        migrations.RemoveField(
            model_name='tourrequest',
            name='status',
        ),
    ]
