# Generated by Django 6.0.3 on 2026-03-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_mpesapayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='agent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='agent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
