# Generated by Django 6.0.3 on 2026-04-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_apartment_agent_email_apartment_agent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paypal_order_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
