# Generated by Django 6.0.3 on 2026-04-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_payment_paypal_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
